version: '3.8'

services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "8080:8080"
    networks:
      - backend_network  # Red donde está el backend

  backend:
    build:
      context: ./BackEnd
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=agronomico
      - DB_PORT=3306
    networks:
      - backend_network  # Red donde está la base de datos y el frontend
      
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agronomico
    ports:
      - "3307:3306"  # Exponer el puerto de MySQL
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
